### ISSUE TITLE
 possibility to recover channel points and "participate" in drops

### ISSUE THREAD

**Issue by rjousse18** [MrSprigster/Twitch.tv-on-XBMC#617] opened 2022-02-11 15:11 UTC
### What Problem Does This Solve? 

Please provide a concise description of the problem this request solves.

I just want to ask if it's possible to get channel points and drop directly from this add-on.

------

### Suggest a Solution (optional)

Please provide a concise description of your suggested solution. If there are multiple solutions, describe them independently and optionally follow them with a comparison.

I don't know, but maybe it's possible to have a pop-up like "skip intro" in the netflix add on ?

------

**Comment by anxdpanic** [comment] 2022-02-11 16:42
duplicate of #580

**Closed as completed by anxdpanic** 2022-02-11 16:42 UTC
Labels: enhancement
